export const fakeETFsData = [
    {
        logo: "https://cdn.moning.co/logos/lyxor.png",
        name: "Lyxor MSCI China UCITS ETF - Acc CHF",
        ticker: "LCCN",
        country: "FR",
        exposition: "CAC 40",
        price: 25,
        yield: 70,
        fees: 28,
        ESGScore: "A+",
        priceOver1Year: 0
    },
    {
        logo: "https://cdn.moning.co/logos/amundi.png",
        name: "Amundi Index Solutions - Amundi MSCI China UCITS ETF-C EUR",
        ticker: "CC1",
        country: "CH",
        exposition: "Chine",
        price: 45,
        yield: 80,
        fees: 2,
        ESGScore: "B+",
        priceOver1Year: 12
    },
    {
        logo: "https://cdn.moning.co/logos/etf.png",
        name: "SPDR S&P 500 ETF Trust",
        ticker: "SPY",
        country: "US",
        exposition: "S&P 500",
        price: 7,
        yield: 41,
        fees: 20,
        ESGScore: "C-",
        priceOver1Year: 7
    },
    {
        logo: "https://cdn.moning.co/logos/ishares.png",
        name: "iShares Core S&P 500 ETF",
        ticker: "IVV",
        country: "US",
        exposition: "US",
        price: 89,
        yield: 71,
        fees: 75.78,
        ESGScore: "B+",
        priceOver1Year: 13
    },
    {
        logo: "https://cdn.moning.co/logos/vanguard.png",
        name: "Vanguard Total Stock Market Index Fund ETF Shares",
        ticker: "VOO",
        country: "US",
        exposition: "US",
        price: 379,
        yield: 1.59,
        fees: 0.15,
        ESGScore: "C+",
        priceOver1Year: -6
    },
    {
        logo: "https://cdn.moning.co/logos/lyxor.png",
        name: "Lyxor MSCI China UCITS ETF - Acc CHF",
        ticker: "LCCN",
        country: "FR",
        exposition: "CAC 40",
        price: 25,
        yield: 70,
        fees: 28,
        ESGScore: "A+",
        priceOver1Year: 0
    },
    {
        logo: "https://cdn.moning.co/logos/amundi.png",
        name: "Amundi Index Solutions - Amundi MSCI China UCITS ETF-C EUR",
        ticker: "CC1",
        country: "CH",
        exposition: "Chine",
        price: 45,
        yield: 80,
        fees: 2,
        ESGScore: "B+",
        priceOver1Year: 12
    },
    {
        logo: "https://cdn.moning.co/logos/etf.png",
        name: "SPDR S&P 500 ETF Trust",
        ticker: "SPY",
        country: "US",
        exposition: "S&P 500",
        price: 7,
        yield: 41,
        fees: 20,
        ESGScore: "C-",
        priceOver1Year: 7
    },
    {
        logo: "https://cdn.moning.co/logos/ishares.png",
        name: "iShares Core S&P 500 ETF",
        ticker: "IVV",
        country: "US",
        exposition: "US",
        price: 89,
        yield: 71,
        fees: 75.78,
        ESGScore: "B+",
        priceOver1Year: 13
    },
    {
        logo: "https://cdn.moning.co/logos/vanguard.png",
        name: "Vanguard Total Stock Market Index Fund ETF Shares",
        ticker: "VOO",
        country: "US",
        exposition: "US",
        price: 379,
        yield: 1.59,
        fees: 0.15,
        ESGScore: "C+",
        priceOver1Year: -6
    },
    {
        logo: "https://cdn.moning.co/logos/lyxor.png",
        name: "Lyxor MSCI China UCITS ETF - Acc CHF",
        ticker: "LCCN",
        country: "FR",
        exposition: "CAC 40",
        price: 25,
        yield: 70,
        fees: 28,
        ESGScore: "A+",
        priceOver1Year: 0
    },
    {
        logo: "https://cdn.moning.co/logos/amundi.png",
        name: "Amundi Index Solutions - Amundi MSCI China UCITS ETF-C EUR",
        ticker: "CC1",
        country: "CH",
        exposition: "Chine",
        price: 45,
        yield: 80,
        fees: 2,
        ESGScore: "B+",
        priceOver1Year: 12
    },
    {
        logo: "https://cdn.moning.co/logos/etf.png",
        name: "SPDR S&P 500 ETF Trust",
        ticker: "SPY",
        country: "US",
        exposition: "S&P 500",
        price: 7,
        yield: 41,
        fees: 20,
        ESGScore: "C-",
        priceOver1Year: 7
    },
    {
        logo: "https://cdn.moning.co/logos/ishares.png",
        name: "iShares Core S&P 500 ETF",
        ticker: "IVV",
        country: "US",
        exposition: "US",
        price: 89,
        yield: 71,
        fees: 75.78,
        ESGScore: "B+",
        priceOver1Year: 13
    },
    {
        logo: "https://cdn.moning.co/logos/vanguard.png",
        name: "Vanguard Total Stock Market Index Fund ETF Shares",
        ticker: "VOO",
        country: "US",
        exposition: "US",
        price: 379,
        yield: 1.59,
        fees: 0.15,
        ESGScore: "C+",
        priceOver1Year: -6
    },
    {
        logo: "https://cdn.moning.co/logos/lyxor.png",
        name: "Lyxor MSCI China UCITS ETF - Acc CHF",
        ticker: "LCCN",
        country: "FR",
        exposition: "CAC 40",
        price: 25,
        yield: 70,
        fees: 28,
        ESGScore: "A+",
        priceOver1Year: 0
    },
    {
        logo: "https://cdn.moning.co/logos/amundi.png",
        name: "Amundi Index Solutions - Amundi MSCI China UCITS ETF-C EUR",
        ticker: "CC1",
        country: "CH",
        exposition: "Chine",
        price: 45,
        yield: 80,
        fees: 2,
        ESGScore: "B+",
        priceOver1Year: 12
    },
    {
        logo: "https://cdn.moning.co/logos/etf.png",
        name: "SPDR S&P 500 ETF Trust",
        ticker: "SPY",
        country: "US",
        exposition: "S&P 500",
        price: 7,
        yield: 41,
        fees: 20,
        ESGScore: "C-",
        priceOver1Year: 7
    },
    {
        logo: "https://cdn.moning.co/logos/ishares.png",
        name: "iShares Core S&P 500 ETF",
        ticker: "IVV",
        country: "US",
        exposition: "US",
        price: 89,
        yield: 71,
        fees: 75.78,
        ESGScore: "B+",
        priceOver1Year: 13
    },
    {
        logo: "https://cdn.moning.co/logos/vanguard.png",
        name: "Vanguard Total Stock Market Index Fund ETF Shares",
        ticker: "VOO",
        country: "US",
        exposition: "US",
        price: 379,
        yield: 1.59,
        fees: 0.15,
        ESGScore: "C+",
        priceOver1Year: -6
    },
    {
        logo: "https://cdn.moning.co/logos/lyxor.png",
        name: "Lyxor MSCI China UCITS ETF - Acc CHF",
        ticker: "LCCN",
        country: "FR",
        exposition: "CAC 40",
        price: 25,
        yield: 70,
        fees: 28,
        ESGScore: "A+",
        priceOver1Year: 0
    },
    {
        logo: "https://cdn.moning.co/logos/amundi.png",
        name: "Amundi Index Solutions - Amundi MSCI China UCITS ETF-C EUR",
        ticker: "CC1",
        country: "CH",
        exposition: "Chine",
        price: 45,
        yield: 80,
        fees: 2,
        ESGScore: "B+",
        priceOver1Year: 12
    },
    {
        logo: "https://cdn.moning.co/logos/etf.png",
        name: "SPDR S&P 500 ETF Trust",
        ticker: "SPY",
        country: "US",
        exposition: "S&P 500",
        price: 7,
        yield: 41,
        fees: 20,
        ESGScore: "C-",
        priceOver1Year: 7
    },
    {
        logo: "https://cdn.moning.co/logos/ishares.png",
        name: "iShares Core S&P 500 ETF",
        ticker: "IVV",
        country: "US",
        exposition: "US",
        price: 89,
        yield: 71,
        fees: 75.78,
        ESGScore: "B+",
        priceOver1Year: 13
    },
    {
        logo: "https://cdn.moning.co/logos/vanguard.png",
        name: "Vanguard Total Stock Market Index Fund ETF Shares",
        ticker: "VOO",
        country: "US",
        exposition: "US",
        price: 379,
        yield: 1.59,
        fees: 0.15,
        ESGScore: "C+",
        priceOver1Year: -6
    },
];