export const tableElements = [
    {
        logo: "https://eodhistoricaldata.com/img/logos/PA/tte.png",
        name: "TotalEnergies SE shlekk mhmd koubar baddeh enka7o",
        ticker: "TTE",
        country: "France",
        sector: "Énergie",
        price: 59.35,
        PER: 8.5,
        yield: 4.73,
        divUninter: 30,
        divScore: 19,
        croissanceScore: 3,
        priceOver1Year: 22,
        addedToWatchList: true,
        isPro: false
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/aapl.png",
        name: "Apple Inc",
        ticker: "AAPL",
        country: "US",
        sector: "Technologie",
        price: 151,
        PER: 37,
        yield: 0.61,
        divUninter: 11,
        divScore: 3,
        croissanceScore: 8,
        priceOver1Year: -10,
        isPro: false
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/o.png",
        name: "Reality Income Corp",
        ticker: "O",
        country: "US",
        sector: "Immobilier",
        price: 66.85,
        PER: 550,
        yield: 4.5,
        divUninter: 29,
        divScore: 3,
        croissanceScore: 15,
        priceOver1Year: 4,
        addedToWatchList: true,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/ko.png",
        name: "Coca-Cola Co",
        ticker: "KO",
        country: "US",
        sector: "Consommation courante",
        price: 472550,
        PER: 25,
        yield: 2.95,
        divUninter: 30,
        divScore: undefined,
        croissanceScore: 5,
        priceOver1Year: 2,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/MSFT.png",
        name: "Microsoft Corporation",
        ticker: "MSFT",
        country: "US",
        sector: "Technologie",
        price: 263,
        PER: 5.5,
        yield: 1.03,
        divUninter: 20,
        divScore: 3,
        croissanceScore: 19,
        priceOver1Year: -10,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/amzn.png",
        name: "Amazon.com Inc",
        ticker: "AMZN",
        country: "US",
        sector: "Consommation discrétionnaire",
        price: 99.54,
        PER: 5.5,
        yield: 0,
        divUninter: undefined,
        divScore: undefined,
        croissanceScore: undefined,
        priceOver1Year: -36,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/PA/tte.png",
        name: "TotalEnergies SE",
        ticker: "TTE",
        country: "France",
        sector: "Énergie",
        price: 59.35,
        PER: 8.5,
        yield: 4.73,
        divUninter: 30,
        divScore: 19,
        croissanceScore: 3,
        priceOver1Year: 22,
        addedToWatchList: true,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/PA/tte.png",
        name: "TotalEnergies SE shlekk mhmd koubar baddeh enka7o",
        ticker: "TTE",
        country: "France",
        sector: "Énergie",
        price: 59.35,
        PER: 8.5,
        yield: 4.73,
        divUninter: 30,
        divScore: 19,
        croissanceScore: 3,
        priceOver1Year: 22,
        addedToWatchList: true,
        isPro: false
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/aapl.png",
        name: "Apple Inc",
        ticker: "AAPL",
        country: "US",
        sector: "Technologie",
        price: 151,
        PER: 37,
        yield: 0.61,
        divUninter: 11,
        divScore: 3,
        croissanceScore: 8,
        priceOver1Year: -10,
        isPro: false
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/o.png",
        name: "Reality Income Corp",
        ticker: "O",
        country: "US",
        sector: "Immobilier",
        price: 66.85,
        PER: 550,
        yield: 4.5,
        divUninter: 29,
        divScore: 3,
        croissanceScore: 15,
        priceOver1Year: 4,
        addedToWatchList: true,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/ko.png",
        name: "Coca-Cola Co",
        ticker: "KO",
        country: "US",
        sector: "Consommation courante",
        price: 472550,
        PER: 25,
        yield: 2.95,
        divUninter: 30,
        divScore: undefined,
        croissanceScore: 5,
        priceOver1Year: 2,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/MSFT.png",
        name: "Microsoft Corporation",
        ticker: "MSFT",
        country: "US",
        sector: "Technologie",
        price: 263,
        PER: 5.5,
        yield: 1.03,
        divUninter: 20,
        divScore: 3,
        croissanceScore: 19,
        priceOver1Year: -10,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/amzn.png",
        name: "Amazon.com Inc",
        ticker: "AMZN",
        country: "US",
        sector: "Consommation discrétionnaire",
        price: 99.54,
        PER: 5.5,
        yield: 0,
        divUninter: undefined,
        divScore: undefined,
        croissanceScore: undefined,
        priceOver1Year: -36,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/PA/tte.png",
        name: "TotalEnergies SE",
        ticker: "TTE",
        country: "France",
        sector: "Énergie",
        price: 59.35,
        PER: 8.5,
        yield: 4.73,
        divUninter: 30,
        divScore: 19,
        croissanceScore: 3,
        priceOver1Year: 22,
        addedToWatchList: true,
        isPro: true
    }, {
        logo: "https://eodhistoricaldata.com/img/logos/PA/tte.png",
        name: "TotalEnergies SE shlekk mhmd koubar baddeh enka7o",
        ticker: "TTE",
        country: "France",
        sector: "Énergie",
        price: 59.35,
        PER: 8.5,
        yield: 4.73,
        divUninter: 30,
        divScore: 19,
        croissanceScore: 3,
        priceOver1Year: 22,
        addedToWatchList: true,
        isPro: false
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/aapl.png",
        name: "Apple Inc",
        ticker: "AAPL",
        country: "US",
        sector: "Technologie",
        price: 151,
        PER: 37,
        yield: 0.61,
        divUninter: 11,
        divScore: 3,
        croissanceScore: 8,
        priceOver1Year: -10,
        isPro: false
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/o.png",
        name: "Reality Income Corp",
        ticker: "O",
        country: "US",
        sector: "Immobilier",
        price: 66.85,
        PER: 550,
        yield: 4.5,
        divUninter: 29,
        divScore: 3,
        croissanceScore: 15,
        priceOver1Year: 4,
        addedToWatchList: true,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/ko.png",
        name: "Coca-Cola Co",
        ticker: "KO",
        country: "US",
        sector: "Consommation courante",
        price: 472550,
        PER: 25,
        yield: 2.95,
        divUninter: 30,
        divScore: undefined,
        croissanceScore: 5,
        priceOver1Year: 2,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/MSFT.png",
        name: "Microsoft Corporation",
        ticker: "MSFT",
        country: "US",
        sector: "Technologie",
        price: 263,
        PER: 5.5,
        yield: 1.03,
        divUninter: 20,
        divScore: 3,
        croissanceScore: 19,
        priceOver1Year: -10,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/US/amzn.png",
        name: "Amazon.com Inc",
        ticker: "AMZN",
        country: "US",
        sector: "Consommation discrétionnaire",
        price: 99.54,
        PER: 5.5,
        yield: 0,
        divUninter: undefined,
        divScore: undefined,
        croissanceScore: undefined,
        priceOver1Year: -36,
        isPro: true
    },
    {
        logo: "https://eodhistoricaldata.com/img/logos/PA/tte.png",
        name: "TotalEnergies SE",
        ticker: "TTE",
        country: "France",
        sector: "Énergie",
        price: 59.35,
        PER: 8.5,
        yield: 4.73,
        divUninter: 30,
        divScore: 19,
        croissanceScore: 3,
        priceOver1Year: 22,
        addedToWatchList: true,
        isPro: true
    },
];
